# numpy
 - ndarray

In [1]:
import numpy as np

In [3]:
# np.array()
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [4]:
x.shape   # 차수 : axis=0, axis=1

(4,)

In [120]:
# np.ndarray() 클래스
x = np.ndarray(shape=(4,5))
x

array([[5.98193043e-154, 1.15312601e+214, 1.21698086e-152,
        3.62479373e+228, 3.68067498e+180],
       [5.75678486e+252, 1.81596891e-152, 2.44087561e-154,
        2.61261326e+257, 1.10755182e+054],
       [9.78375158e+199, 4.24387585e+222, 5.22376873e+257,
        2.69271725e+161, 2.69271725e+161],
       [6.32976576e-119, 1.48301412e+185, 7.53046676e+252,
        5.98185637e-154, 6.99497719e+228]])

In [121]:
x.shape

(4, 5)

In [122]:
x.ndim

2

In [123]:
x.size

20

In [12]:
x.dtype  # 데이터형식

dtype('float64')

데이터 형식 : 약어 + 바이트 수

In [124]:
# np.ndarray() 클래스
x = np.ndarray(shape=(4,5), dtype=np.float32)  
x

array([[0.       , 4.9765625, 0.       , 0.       , 0.       ],
       [5.232422 , 0.       , 0.       , 0.       , 5.4765625],
       [0.       , 0.       , 0.       , 5.6103516, 0.       ],
       [0.       , 0.       , 5.732422 , 0.       , 0.       ]],
      dtype=float32)

In [125]:
# 약어
x = np.ndarray(shape=(4,5), dtype='f4')  # f4 -> float 4btye
x

array([[0.       , 4.9765625, 0.       , 0.       , 0.       ],
       [5.232422 , 0.       , 0.       , 0.       , 5.4765625],
       [0.       , 0.       , 0.       , 5.6103516, 0.       ],
       [0.       , 0.       , 5.732422 , 0.       , 0.       ]],
      dtype=float32)

In [126]:
x = np.arange(30, 100, 2)
x.shape

(35,)

In [127]:
x

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96,
       98])

In [128]:
x.dtype

dtype('int32')

In [117]:
x.ndim

1

# slicing
 - 전통적 : index, slicing
 - fancy
 - boolean

In [129]:
# 전통적인 방법
x[0]

30

In [20]:
x[0:5]

array([30, 32, 34, 36, 38])

In [21]:
x[:-5]

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88])

In [22]:
x[-10:]

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [23]:
x[0] = -30.1
x[0]

-30

In [25]:
x[0:2] = [-1.0, -2.0]
x[:5]

array([-1, -2, 34, 36, 38])

In [26]:
# fancy
x[[3, 4, -10, -20]]  # index position

array([36, 38, 80, 60])

In [27]:
# boolean
x < 10

array([ True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False])

In [28]:
x[ x < 10 ]

array([-1, -2])

## reshape

In [30]:
x.shape  # 1차원 배열 -> 벡터!!

(35,)

In [130]:
z = np.reshape(x, (1, 35))
z

array([[30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60,
        62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92,
        94, 96, 98]])

In [131]:
z.shape

(1, 35)

In [132]:
z = np.reshape(x, (5, -1))
z

array([[30, 32, 34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68, 70],
       [72, 74, 76, 78, 80, 82, 84],
       [86, 88, 90, 92, 94, 96, 98]])

In [133]:
z.shape

(5, 7)

In [134]:
np.reshape(x, (1,1,-1))

array([[[30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60,
         62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92,
         94, 96, 98]]])

## pickle 저장  
 - 파이썬의 다른 프로그램에서 사용할 수 있도록 저장

In [135]:
np.save('np_z', z)

In [136]:
%ls *.npy

 C 드라이브의 볼륨: Windows
 볼륨 일련 번호: 8EF6-8BCC

 C:\Users\SBAUser\jupyter-work 디렉터리

2022-11-28  오전 11:41               268 np_z.npy
2022-11-25  오후 02:21         8,000,128 npydata.npy
               2개 파일           8,000,396 바이트
               0개 디렉터리  407,142,588,416 바이트 남음


In [137]:
!more np_z.npy

밡UMPY
v
{'descr': '<i4', 'fortran_order': False, 'shape': (5, 7), }                                                          



 


"


$


&


(


*


,


.


0


2


4


6


8


:


<


>


@


B


D


F


H


J


L


N


P


R


T


V


X


Z


\


^


`


b




In [138]:
k = np.load('np_z.npy')   # dump

In [139]:
type(k)

numpy.ndarray

In [140]:
k.shape

(5, 7)

In [141]:
k[:10]

array([[30, 32, 34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68, 70],
       [72, 74, 76, 78, 80, 82, 84],
       [86, 88, 90, 92, 94, 96, 98]])

# Pandas
 - Series
 - DataFrame : 행/열에 Series

In [51]:
import pandas as pd 

In [52]:
s = pd.Series([10, 20, 30, 40]) # index + value
s

0    10
1    20
2    30
3    40
dtype: int64

In [54]:
s = pd.Series(('안녕', '하세요', '여러분'))
s

0     안녕
1    하세요
2    여러분
dtype: object

In [55]:
s.shape, s.dtype, s.ndim, s.size

((3,), dtype('O'), 1, 3)

In [56]:
pd.Series( np.arange(1,20) )

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
dtype: int32

In [64]:
a = pd.Series( {'1': 20000, '2':30000, '3':40000} ) # dic의 key값이 index로 지정
a

1    20000
2    30000
3    40000
dtype: int64

In [65]:
b = pd.Series( {'a': 20000, 'b':30000, 'c':40000} ) # dic의 key값이 index로 지정
b

a    20000
b    30000
c    40000
dtype: int64

In [67]:
# broadcast 연산, element wide 연산 -> 모든 요소의 위치(index)끼리 연산
a + b         #  index가 다르기 때문 

1   NaN
2   NaN
3   NaN
a   NaN
b   NaN
c   NaN
dtype: float64

In [72]:
a = pd.Series( {'1': 20000, '2':30000, '3':40000} ) 

In [73]:
b = pd.Series( {'1': 20000, '2':30000, '3':40000, '4': 50000} ) 

In [75]:
a + b, b + a

(1    40000.0
 2    60000.0
 3    80000.0
 4        NaN
 dtype: float64,
 1    40000.0
 2    60000.0
 3    80000.0
 4        NaN
 dtype: float64)

In [76]:
a / b

1    1.0
2    1.0
3    1.0
4    NaN
dtype: float64

In [77]:
a * b

1    4.000000e+08
2    9.000000e+08
3    1.600000e+09
4             NaN
dtype: float64

In [80]:
a.add(b)  # a + b 와 같은 결과

1    40000.0
2    60000.0
3    80000.0
4        NaN
dtype: float64

## 연산시 nan 처리
 - fill_value : 연산시 nan 채우고 연산!
 - Series/DataFrame.fillna() : 데이터의 nan을 어떤 값으로 채움

In [98]:
a1 = a.add(b, fill_value=0)  # 비어있는  a의 nan을 0으로 채운 후 연산
a1

1    40000.0
2    60000.0
3    80000.0
4    50000.0
dtype: float64

In [83]:
a2 = a + b

In [97]:
a2.fillna(0)   # 연산 후 나온 nan 값을 0으로 채움

1    40000.0
2    60000.0
3    80000.0
4        0.0
dtype: float64

In [90]:
a1, a2

(1    40000.0
 2    60000.0
 3    80000.0
 4    50000.0
 dtype: float64,
 1    40000.0
 2    60000.0
 3    80000.0
 4        NaN
 dtype: float64)

In [91]:
a1.mean(), a2.mean()

(57500.0, 60000.0)

In [92]:
a3 = a + b

In [93]:
a3

1    40000.0
2    60000.0
3    80000.0
4        NaN
dtype: float64

In [103]:
a3.fillna(0)

1    40000.0
2    60000.0
3    80000.0
4        0.0
dtype: float64

In [104]:
a3.fillna(0, inplace=True)  
a3

1    40000.0
2    60000.0
3    80000.0
4        0.0
dtype: float64

# Series 인덱싱
 - 전통적 `[]` 연산자
 - iloc
 - loc

In [105]:
s = pd.Series({'서울': 2000, '대구' : 3000, '부산' : 4000, '광주' : 5000, '대전' : 6000})
s

서울    2000
대구    3000
부산    4000
광주    5000
대전    6000
dtype: int64

In [107]:
# index position
s[0], s[0:2], s[:-2], s[-3:]

(2000,
 서울    2000
 대구    3000
 dtype: int64,
 서울    2000
 대구    3000
 부산    4000
 dtype: int64,
 부산    4000
 광주    5000
 대전    6000
 dtype: int64)

In [108]:
s.index

Index(['서울', '대구', '부산', '광주', '대전'], dtype='object')

In [109]:
s['서울'], s['서울':'부산']

(2000,
 서울    2000
 대구    3000
 부산    4000
 dtype: int64)

In [111]:
s [ :, : ]  # 1차원 데이터

KeyError: 'key of type tuple not found and not a MultiIndex'